stages:
    - build
    - test
    - deploy

test tac:
    stage: test
    tags:
         - ruby_1
    script:
          - rspec spec/cell_spec.rb
        # -  ruby example/example_game.rb
variables:
    RUBY_VERSION: '2.7'
    
build tac:
    stage: build
    tags:
        - ruby_1
    script:
        - bundle gem tic_tac_toe

deploy tac:
    stage: deploy
    tags:
        - ruby_1
    script:
        # - ruby example/example_game.rb
        - echo "Deploying Tic-Tac-Toe game"

build app:
  image: golang:latest
  stage: build
  script:
    - go build -o app main.go
  artifacts:
    paths:
      - app
    expire_in: 1 hour


